### ISSUE TITLE
Research | Launch Ethnio and recruit participants for certification research

### ISSUE THREAD

**Issue by mkhandekar** [cagov/unemployment#177]
To be able to systemize the recruiting process and to reach a more representative participant pool, we will:

- [x] Get an Ethnio training/onboarding/account
- [x] Meet with Jodi for initial walkthrough
- [x] Write screener for Ethnio
- [x] Send out Ethnio to social media, FB groups, Slack groups

**Comment by mkhandekar** [comment]
I have an account, and have received a high level overview of the product.

**Comment by mkhandekar** [comment]
We used Ethnio solely to recruit, communicate with, schedule sessions and pay incentives. 🎉
