### ISSUE TITLE
Research | Certification | Conduct usability testing

### ISSUE THREAD

**Issue by mkhandekar** [cagov/unemployment#179]
Conduct usability research with prototypes made in #219 and content written in #218 

Meghan: `2.5 points`
Tina: `2.5 points`
Total: `approx 5 days`

Meghana supporting.

**Comment by nguyen-tina** [comment]
Things that need to be done before Usability Testing on Monday:

- [ ] Update Confirmation Screen in prototype with new content (Meghan)
- [ ] Update Content Active Draft with removed Week Verification page
- [ ] Update Raw Notes to match Moderator Guide
