### ISSUE TITLE
Design | Certification | Iterate on user flow and high fidelity design prototypes

### ISSUE THREAD

**Issue by mkhandekar** [cagov/unemployment#219]
Tina completed #178 in Sprint 3, this captures further refinement to the prototype, accounting for:

- [x] Help text
- [x] 4 variations of questions 
- [x] Meetings and soliciting feedback from EDD/ODI
- [x] Coordination / collaboration with @meghscase on content iteration
- [x] Incorporating feedback into the prototypes
- [x] Incorporating changes to prototypes, based on what we learn from usability testing #179 
- [x] Coordination / collaboration with @sharonwarner on engineering feasibility

**Comment by nguyen-tina** [comment]
High fidelity mocks are mostly complete! Still need to show the accordion expansion interaction for Questions 
![6 – Certifying v3 1](https://user-images.githubusercontent.com/17328158/83190133-f1ad6a00-a0ff-11ea-8ee4-53c8b5294fd7.png)
![2 – Certification Weeks](https://user-images.githubusercontent.com/17328158/83190151-f6721e00-a0ff-11ea-9e9d-b97491b58737.png)

**Comment by nguyen-tina** [comment]
Meghana sent out draft content to UIB and PAB on 6/2

We are currently on v3.1 of the prototype. Currently, I'm working on designing the header area

**Comment by nguyen-tina** [comment]
Find Me Page
![0 1 – Sign in](https://user-images.githubusercontent.com/17328158/85329524-aa1cc280-b4a0-11ea-8537-9ebb208cebde.png)

**Comment by nguyen-tina** [comment]
Next Steps Page

![1 0 – Home with Sign in Success](https://user-images.githubusercontent.com/17328158/85330098-bd7c5d80-b4a1-11ea-8003-5bb42b5ea94c.png)

**Comment by nguyen-tina** [comment]
Certifying the First Week

![2 0 – Certifying First Week](https://user-images.githubusercontent.com/17328158/85337022-ae9ba800-b4ad-11ea-8afd-4d7f42454f9b.png)

**Comment by nguyen-tina** [comment]
Certifying the last week (in-line error shown)

![3 1 – Last Certifying Week](https://user-images.githubusercontent.com/17328158/85340173-9dee3080-b4b3-11ea-8d1a-b2be4a9ee708.png)

Note: "Back" button text changes for weekly certifications

**Comment by nguyen-tina** [comment]
Submission/Confirmation page

![4 0 – Confirmation](https://user-images.githubusercontent.com/17328158/85340225-b6f6e180-b4b3-11ea-9c76-53d16fbee038.png)

**Comment by nguyen-tina** [comment]
Returning User Page

[5.0 – Returning User.pdf](https://github.com/cagov/unemployment/files/4815812/5.0.Returning.User.pdf)
