### ISSUE TITLE
Research | Guide | Organize and share findings

### ISSUE THREAD

**Issue by mkhandekar** [cagov/unemployment#224]
- [x] Finalize writing research findings written in https://github.com/cagov/unemployment/issues/89 
- [ ] _Think about if this needs to be a presentation with screenshots, though this could happen after we prioritize recommendations_ 
- [x] Export and share with ODI, EDD, Alpha team
- [ ] _If it is a presentation, schedule and share as presentation_
