### ISSUE TITLE
Implement partial save (or, save your progress)

### ISSUE THREAD

**Issue by sharonwarner** [cagov/unemployment#277]
This requires additional research before breaking up into multiple tickets.

User value: high
Business value: medium - will improve participation rate
Level of effort: implement on Wednesday 6/24

**Comment by mkhandekar** [comment]
Potential sub-tickets from the Product Spec:
* Partial save every time a user completes a week. 
* User will still lose the week-in-progress if the page gets refreshed. 
* When log back in, answers will be filled in. 

Design questions:
- what does the user see when they got in after they have been timed out? Will it be a version of the confirmation page?
- Will they go through each of the filled out weeks to get to the unfinished weeks, or will they skip the filled out weeks?
- Do the buttons / CTA's change depending on if a user has fully submitted vs partially saved?

**Comment by mthong** [comment]
Question:
When I talked with Sharon about this feature earlier this week, it sounded like it would be fairly subtle to the user -- the data would get automatically saved when they clicked on the "Next Week" button but they would not be able to explicitly "Save Draft" or "Save" their data in the middle of a week. I'm curious how much more work it would be to add a "Save" button that would make the feature more self-explanatory to the user -- and also allow them to save the current week in progress -- otherwise my understanding is they will lose a week in progress. If it is not significantly more work, it may be worth considering.

**Comment by kalvinwang** [comment]
@mthong  I'm not sure exactly how much more eng work it'll be, but I'll figure it out while working on this ticket! That would be a great feature to have.

**Comment by mthong** [comment]
Based on our conversation this morning, it sounds like it may be easier to get agreement with EDD on the subtle implementation and then consider beefing that up to a more explicit Save feature post launch.

**Comment by nguyen-tina** [comment]
Ok! Some changes! 

- [ ] Update text under Important Information
- [ ] For Weeks 2+, add text to the top (You are on Week X of X weeks to retroactively certify. Your previous weeks are saved.)
- [ ] WHEN A USER 'FINDS ME' AFTER BEING LOGGED OUT, land them on the week they have NOT saved and display a validation banner at the top.  I.e., if they've saved 2 weeks, land them on Week 3.
![3 0 – Last Certifying Week](https://user-images.githubusercontent.com/17328158/85616948-6e166880-b62c-11ea-955f-c56a8626bf0c.png)

**Comment by idealisms** [comment]
We can also update the Next button to say "Save and continue to week X" or something. Also, we could have it auto save before the session timeout, although maybe that's weird since it's not an explicit user action.

**Comment by nguyen-tina** [comment]
I support Tony's "Save and Continue to Week X" to make it EXTRA clear.

**Comment by kalvinwang** [comment]
@idealisms thanks for taking this on! yeah, for a followup ticket, i think it'd be useful to understand how much effort an auto save feature would be, whether after each field/section or before the timeout, so we can take that into account when deciding whether it's a good idea to implement that next!

**Comment by idealisms** [comment]
I don't think saving more frequently (or an explicit save button) would be hard to implement, but if we save too frequently, we may DDoS ourselves.

**Comment by mthong** [comment]
Proposed documentation to share for review by EDD:

Current state:The app does not save data for a claimant. If they timeout or refresh the screen before submitting, they will lose all weeks that they have entered. 

Proposed future state: 
1) The app will save each week of data when the user progresses to the next week. To inform the user of this feature, we propose adding the text under the "Important Information" section: "Your answers for each weekly certification will be saved automatically once you certify for the next week. Partially-completed weeks are not saved. Try to complete all retroactive certifications in one session." This will go immediately before the information on the 30 minute timeout. 
2) The button at the bottom of the app, currently labeled "Next, Certify Week X" will be changed to "Save and Continue to Week X" 
3) If a user timeouts or refreshes the app partway through one of the weeks, they will have to log back in. 
4) When the user logs back in and the app finds they have 1 or more weeks of saved data, they will see this message: 
"You are on Week X of X weeks to retroactively certify. Your previous weeks are saved." They will be on the first week they have not saved.

**Comment by kalvinwang** [comment]
@mthong Haha yeah. But let's say for saving before timeout, "not hard" could be 30 minutes or 8 hours, and if it's 30 minutes, we might want to prioritize it higher.

**Comment by kalvinwang** [comment]
@idealisms oops, the message above was meant for you, i absent-mindedly wrote michelle

**Comment by mkhandekar** [comment]
This is what we sent EDD:

# New feature: partial saving of the application

"Partial saving" is an improvement we recommend implementing to ensure that users do not accidentally lose all of their work if the app accidentally refreshes while they are in progress. It was not in our original requirements but it would be a relatively low additional engineering effort to implement before launch, would potentially increase the completion rate for users, and would reduce user pain points related to the 30 minute timeout. 

Here is the proposal for the feature. Let us know if you have questions or concerns, and if you approve of this feature and the associated content.  If you approve the feature, we can implement it in time for testing before the end of the week. We recognize that there are several additional lines of content that will have to be approved by UIB and PAB, and translated, if you were to approve this feature. 

### Current state:

- The app does not save data for a claimant. 
- If a user times out or refreshes the screen before submitting, they will lose all weeks that they have entered and will have to start from the beginning. 

### Proposed future state:

- The app will save each week of data when the user progresses to the next week. To inform the user of this feature, we propose adding the text under the "Important Information" section, this will go immediately before the information on the 30 minute timeout.
  - “Your answers for each weekly certification will be saved automatically once you continue to the next week. Partially completed weeks are not saved. Try to complete all retroactive certifications in one session.”
- The button at the bottom of the app, currently labeled "Next, Certify Week X" will be changed to "Save and Continue to Week X"
- At the top of all weeks beyond Week 1, for all users, we will let the user know, “You are on Week 2 of 3 weeks to retroactively certify. Your previous weeks are saved.”
- If a user refreshes their browser in the middle of filling in the information for a given week, they will lose the in-progress week, but data for previous completed weeks will be saved.
- When the user logs back in after being timed out or leaving, AND the app finds they have 1 or more weeks of saved data, after hitting the "Find me" button, they will automatically land on the latest week they need to certify. They will see this message: “We found your information! Pick up where you last left off. Your previous weeks have been saved.”

[See Active Draft for where new content appears for Partial Save.](https://docs.google.com/document/u/1/d/1WdMsc_nId5PH7qFLwCFlTImLU1SiQ0QhtJA3OfYBNbo/edit)

**Comment by mkhandekar** [comment]
Approved and translated by EDD and PAB
