### ISSUE TITLE
Ongoing design and engineering tweaks to refine Retro Cert application

### ISSUE THREAD

**Issue by sharonwarner** [cagov/unemployment#333]
### Login page:

- [x] Remove "help us find you" text
- [x] Add asterisks for required fields (also aria-required)
- [x] "Show" should be not bold and update to say Show SSN and Hide SSN

### Question pages:

- [x] Remove green validation text
- [x] Make help text bigger and increase contrast
- [x] Bold question text
- [x] Change every back button during the week-to-week experience to say "Back to previous week"

### Confirmation page:

- [x] Remove confirmation number

### Post MVP Ideas
- [ ] Do we want to include the Day in the weeks? I.e., Sunday, MM/DD/YYYY – Saturday, MM/DD/YYYY? Currently, we introduce it as such on Page 2, but we don’t carry it through in the heading during the Certification experience.
- [ ] The confirmation page and returning page are the exact same, except for the addition of one sentence in the validation banner when a user returns: “No further action is required.” Kalvin proposed that we add this sentence to the confirmation page, so that they’ll be identical no matter what. I’m ok with this, but then I wonder what other utility the Returning page might have.

**Comment by nguyen-tina** [comment]
**Login page**
- [ ] Change padding to 4rem 1.5rem! (so that there's 64px padding top + bottom)
- [ ] Change the intro text at the top to what's in the Active Draft
- [ ] Increase spacing of each form-group to 1.5rem (so that there's 24px spacing between each input field)
- [ ] Increase margin after intro paragraph to 2rem
- [ ] The page width was originally designed to have a max width of 712px. I'm ok with bumping it up to 800px in order to fit the entire text of the title on one line!

**Comment by nguyen-tina** [comment]
### Question pages

- [ ] Max page width: 800px
- [ ] Change margin of m2 to .5rem 0rem! (so that the grey boxes line up with the header text)
- [ ] Radio buttons should be middle aligned to top line of text

**Comment by mkhandekar** [comment]
The successful (green) alerts at the top of the screen stretch to match the width of the max width of the site (when it's done, it should be 800px wide).

Can we make all of the unsuccessful (red) alerts **on all pages** also match the width of the max width of the site?
In fact, all alerts should also match the width of the site.

**Desired:** 

![Screenshot 2020-06-26 16 16 39](https://user-images.githubusercontent.com/1598889/85902066-c2564f80-b7c8-11ea-87ef-cbfd8c1321d6.png)

**Currently wraps to lines:** 

![Screenshot 2020-06-26 16 16 58](https://user-images.githubusercontent.com/1598889/85902163-fa5d9280-b7c8-11ea-87ba-6142204d40b2.png)

**Comment by mthong** [comment]
Let's make sure that anything we change as part of this ticket does not conflict with existing approved text and features. 

For example, I don't think we can bold all question text since there are specific words that EDD wants bolded in the questions, and we wouldn't be able to do that if all words were bold. 

If we need to tweak any of the content previously approved by EDD, we should get approval and Spanish translation before implementing.

**Comment by nguyen-tina** [comment]
**Contrast Updates for Accessibility** 
The low-contrast grey tones are meant to separate the boxes. They’re currently #F8F9FA, but they were originally designed to be #F0F0F0. The most important thing is to have the text be accessible. 

Proposed Changes:
- I propose that we change the grey boxes to be the slightly darker, original color #F0F0F0. An alternative could be #F5F5F5 if we find that too dark.
- Question text needs to have the greatest contrast. It could be black #000000, or #222222 for something less severe, but as strong in contrast (14.59:1 Ratio with #F5F5F5)
- Help text can be #666666 for a 5:1 AA-passing contrast ratio. We can also try making the size smaller (18pt) to de-emphasize.

**Comment by nguyen-tina** [comment]
**Outstanding Changes for Launch**

Certification Pages
- [ ] Move "State" (Under "Employer") To a new line, next to Zip
- [ ] Add padding to Question boxes (1rem)

Sitewide
- [ ] Validation errors should span the entire width of the page (800px). Currently, the unsuccessful messages are half the width, while success messages correctly span the entire width.

**Comment by nguyen-tina** [comment]
It's looking great! There are a few more nit-picky adjustments I would make, non-urget:

**Certification Pages**
- [ ] Header should have 64px from the top + bottom (4rem). This is space between the dropdown menu, and the page title. 
- [ ] Margin bottom of each question block should be 1rem, with no margin at the top.

If possible and with time permitting, I’d like to learn how to adjust the code, view in my own environment, and commit the changes in a PR myself!

**Comment by kalvinwang** [comment]
@nguyen-tina just sent you an invite to finally get you set up with the development environment!
