### ISSUE TITLE
Ensure compatibility across browsers 

### ISSUE THREAD

**Issue by mkhandekar** [cagov/unemployment#337]
For browser testing, you can either use your own computer's browser if you happen to have the correct browsers installed, or use Browserstack. 

We should validate the following features across the following browsers:

- [ ] Chrome 
  - [ ] Ensure login page is formatted cleanly
  - [ ] Attempt to login with missing fields, ensure error is displayed
  - [ ] Attempt to login as an invalid user, ensure error is displayed
  - [ ] Login successfully, ensure you're routed to the landing page
  - [ ] Ensure landing page is formatted cleanly
  - [ ] Attempt to begin certification, ensure you're routed to the first week of questions
  - [ ] Ensure certification questions are formatted cleanly
  - [ ] Across the various weeks, ensure that the followup questions for 1, 2, and 7 are formatted cleanly
  - [ ] Attempt to continue without filling out every field, ensure error is displayed
  - [ ] Go to previous weeks and ensure your answers are still filled out correctly
  - [ ] On the last week's page, attempt to submit without checking the box and ensure error is displayed
  - [ ] Attempt to submit, ensure confirmation page is displayed
  - [ ] Ensure confirmation page is formatted cleanly
- [x] Firefox
  - [x] Ensure login page is formatted cleanly
  - [x] Attempt to login with missing fields, ensure error is displayed
  - [x] Attempt to login as an invalid user, ensure error is displayed
  - [x] Login successfully, ensure you're routed to the landing page
  - [x] Ensure landing page is formatted cleanly
  - [x] Attempt to begin certification, ensure you're routed to the first week of questions
  - [x] Ensure certification questions are formatted cleanly
  - [x] Across the various weeks, ensure that the followup questions for 1, 2, and 7 are formatted cleanly
  - [x] Attempt to continue without filling out every field, ensure error is displayed
  - [x] Go to previous weeks and ensure your answers are still filled out correctly
  - [x] On the last week's page, attempt to submit without checking the box and ensure error is displayed
  - [x] Attempt to submit, ensure confirmation page is displayed
  - [x] Ensure confirmation page is formatted cleanly
- [x] Safari
  - [x] Ensure login page is formatted cleanly
  - [x] Attempt to login with missing fields, ensure error is displayed
  - [x] Attempt to login as an invalid user, ensure error is displayed
  - [x] Login successfully, ensure you're routed to the landing page
  - [x] Ensure landing page is formatted cleanly
  - [x] Attempt to begin certification, ensure you're routed to the first week of questions
  - [x] Ensure certification questions are formatted cleanly
  - [x] Across the various weeks, ensure that the followup questions for 1, 2, and 7 are formatted cleanly
  - [x] Attempt to continue without filling out every field, ensure error is displayed
  - [x] Go to previous weeks and ensure your answers are still filled out correctly
  - [x] On the last week's page, attempt to submit without checking the box and ensure error is displayed
  - [x] Attempt to submit, ensure confirmation page is displayed
  - [x] Ensure confirmation page is formatted cleanly
- [x] IE 11
  - [x] Ensure login page is formatted cleanly
  - [x] Attempt to login with missing fields, ensure error is displayed
  - [x] Attempt to login as an invalid user, ensure error is displayed
  - [x] Login successfully, ensure you're routed to the landing page
  - [x] Ensure landing page is formatted cleanly
  - [x] Attempt to begin certification, ensure you're routed to the first week of questions
  - [x] Ensure certification questions are formatted cleanly
  - [x] Across the various weeks, ensure that the followup questions for 1, 2, and 7 are formatted cleanly
  - [x] Attempt to continue without filling out every field, ensure error is displayed
  - [x] Go to previous weeks and ensure your answers are still filled out correctly
  - [x] On the last week's page, attempt to submit without checking the box and ensure error is displayed
  - [x] Attempt to submit, ensure confirmation page is displayed
  - [x] Ensure confirmation page is formatted cleanly
- [ ] Edge 18
  - [ ] Ensure login page is formatted cleanly
  - [ ] Attempt to login with missing fields, ensure error is displayed
  - [ ] Attempt to login as an invalid user, ensure error is displayed
  - [ ] Login successfully, ensure you're routed to the landing page
  - [ ] Ensure landing page is formatted cleanly
  - [ ] Attempt to begin certification, ensure you're routed to the first week of questions
  - [ ] Ensure certification questions are formatted cleanly
  - [ ] Across the various weeks, ensure that the followup questions for 1, 2, and 7 are formatted cleanly
  - [ ] Attempt to continue without filling out every field, ensure error is displayed
  - [ ] Go to previous weeks and ensure your answers are still filled out correctly
  - [ ] On the last week's page, attempt to submit without checking the box and ensure error is displayed
  - [ ] Attempt to submit, ensure confirmation page is displayed
  - [ ] Ensure confirmation page is formatted cleanly

**Comment by jlechowicz** [comment]
@sharonwarner @nguyen-tina **Here are the results of my first round of testing IE 11 on Windows 10:**

✅Ensure login page is formatted cleanly
✅Attempt to login with missing fields, ensure error is displayed
✅Attempt to login as an invalid user, ensure error is displayed
✅Login successfully, ensure you're routed to the landing page
✅Ensure landing page is formatted cleanly
✅Attempt to begin certification, ensure you're routed to the first week of questions
✅Ensure certification questions are formatted cleanly
✅Across the various weeks, ensure that the followup questions for 1, 2, and 7 are formatted cleanly
❌Attempt to continue without filling out every field, ensure error is displayed
**No error message displayed for sub-question on question 7**
❌Go to previous weeks and ensure your answers are still filled out correctly
**Answer to sub-question on question 7 was not filled in**
✅On the last week's page, attempt to submit without checking the box and ensure error is displayed
✅Attempt to submit, ensure confirmation page is displayed
✅Ensure confirmation page is formatted cleanly

**Comment by KevinJBoyer** [comment]
Great catch -- I unchecked those as I'm seeing the same thing in Firefox.

Confirmed over meeting that question 2 shouldn't have a follow-up. 1 6 7 do show follow ups but question 7 has the issue described above.

**Comment by jdelloso** [comment]
Tested Safari on Mac.  All tests passed.

**Comment by jdelloso** [comment]
Edge 83 tested using browerstack.  All tests passed.

**Comment by jdelloso** [comment]
Edge 18 issues:
The birth day field and birth month field are ONLY accepting 1 to 9.  Any number from 10 on and the system responds "The field is required."
@sharonwarner

**Comment by sharonwarner** [comment]
Thanks Jim! @jlechowicz is looking into that issue.

**Comment by idealisms** [comment]
For reference, the day and month field only accepting one digit is issue #371 .

**Comment by jdelloso** [comment]
@KevinJBoyer Can you update this ticket on Firefox testing?

**Comment by KevinJBoyer** [comment]
I actually just tried it, maybe a couple of minutes before your comment, and was still seeing the same issue.

**Comment by jdelloso** [comment]
Retested Edge 18. Passed all tests.

**Comment by KevinJBoyer** [comment]
Windows 10 + IE11, all tests passed except Q7 follow up (doesn't require follow up to be answered; doesn't remember choice when week is returned to).

**Comment by jdelloso** [comment]
Here is my summary of browser compatibility testing:


Browser | Version | Test Vehicle | Results
- Safari | 13 | MacOS Catalina | Failed on PUA Q7 (Ticket #400)
- Chrome | 83 | MacOS Catalina | Failed on PUA Q7 (Ticket #400)
- Firefox | 77 | MacOS Catalina and Windows 10 on browserstack.com | Failed on PUA Q7 (Ticket #400)
- Internet Explorer | 11 | Windows 10 on browserstack.com | Failed on PUA Q7 (Ticket #400)
- Edge | 83 | browserstack.com using Windows 10 | Failed on PUA Q7 (Ticket #400)
- Edge | 18 | browserstack.com using Windows 10 | Failed on PUA Q7 (Ticket #400)

Essentially, all tests passed except Q7 which is ticket #400
