### ISSUE TITLE
Coordinate with EDD on user acceptance testing

### ISSUE THREAD

**Issue by mkhandekar** [cagov/unemployment#340]
Associated tasks

- [x] send test users (Jim)
- [x] send test status after Wednesday(Jim)
- [x] respond and agree on fixes to Wednesday errors 
- [x] confirm that Wednesday errors have been fixed
- [x] respond and agree on fixes to Thursday errors 
- [x] create and share final punchlist of defects to fix ( Michelle)
- [x] prepare status of tests and defects to present on Monday morning (Michelle)

- [x] Final acceptance of UAT

**Comment by mthong** [comment]
I'm going to break up user acceptance testing and security review into separate tickets. This ticket is now just about UAT, #351, #352 and #353 are about security review.
