### ISSUE TITLE
Make Launch Go/No-Go Decision

### ISSUE THREAD

**Issue by mthong** [cagov/unemployment#350]
As an EDD stakeholder, I want the opportunity to discuss and decide on readiness for launch, so that I can make sure the things I care about are addressed. 

As a retro cert team member, I want to know if our app is lauching on Mon 6/29 or not, so that I can take the appropriate actions to prepare 

- [ ] Get attendee list for launch meeting
- [ ] Schedule launch meeting for Fri 6/26 (possibly Mon 6/29)
- [ ] Conduct launch meeting & make decision
