### ISSUE TITLE
Respond to feedback from third party security review (by Fri 6/26)

### ISSUE THREAD

**Issue by mthong** [cagov/unemployment#352]
- [x] Check in with Martin and Jim on Wednesday to make sure they have what they need and ask for feedback
- [x] Check in with Martin and Jim on Thursday to make sure they have what they need and ask for feedback
- [ ] If there's feedback, review it and confirm how to address with Martin and Jim
