### ISSUE TITLE
Optimize mobile/tablet view

### ISSUE THREAD

**Issue by sharonwarner** [cagov/unemployment#355]
For mobile/tablet testing, you can either use your own device if you have one, or use Browserstack. Login information is in 1password.

We should validate the following features across the following devices:

- [ ] iPhone/safari 
  - [ ] Ensure login page is formatted cleanly
  - [ ] Attempt to login with missing fields, ensure error is displayed
  - [ ] Attempt to login as an invalid user, ensure error is displayed
  - [ ] Login successfully, ensure you're routed to the landing page
  - [ ] Ensure landing page is formatted cleanly
  - [ ] Attempt to begin certification, ensure you're routed to the first week of questions
  - [ ] Ensure certification questions are formatted cleanly
  - [ ] Across the various weeks, ensure that the followup questions for 1, 6, and 7 are formatted cleanly
  - [ ] Attempt to continue without filling out every field, ensure error is displayed
  - [ ] Go to previous weeks and ensure your answers are still filled out correctly
  - [ ] On the last week's page, attempt to submit without checking the box and ensure error is displayed
  - [ ] Attempt to submit, ensure confirmation page is displayed
  - [ ] Ensure confirmation page is formatted cleanly
- [ ] iPad/Safari
  - [ ] Ensure login page is formatted cleanly
  - [ ] Attempt to login with missing fields, ensure error is displayed
  - [ ] Attempt to login as an invalid user, ensure error is displayed
  - [ ] Login successfully, ensure you're routed to the landing page
  - [ ] Ensure landing page is formatted cleanly
  - [ ] Attempt to begin certification, ensure you're routed to the first week of questions
  - [ ] Ensure certification questions are formatted cleanly
  - [ ] Across the various weeks, ensure that the followup questions for 1, 6, and 7 are formatted cleanly
  - [ ] Attempt to continue without filling out every field, ensure error is displayed
  - [ ] Go to previous weeks and ensure your answers are still filled out correctly
  - [ ] On the last week's page, attempt to submit without checking the box and ensure error is displayed
  - [ ] Attempt to submit, ensure confirmation page is displayed
  - [ ] Ensure confirmation page is formatted cleanly
- [x] Samsung Galaxy/Chrome
  - [x] Ensure login page is formatted cleanly
  - [x] Attempt to login with missing fields, ensure error is displayed
  - [x] Attempt to login as an invalid user, ensure error is displayed
  - [x] Login successfully, ensure you're routed to the landing page
  - [x] Ensure landing page is formatted cleanly
  - [x] Attempt to begin certification, ensure you're routed to the first week of questions
  - [x] Ensure certification questions are formatted cleanly
  - [x] Across the various weeks, ensure that the followup questions for 1, 6, and 7 are formatted cleanly
  - [x] Attempt to continue without filling out every field, ensure error is displayed
  - [x] Go to previous weeks and ensure your answers are still filled out correctly
  - [x] On the last week's page, attempt to submit without checking the box and ensure error is displayed
  - [x] Attempt to submit, ensure confirmation page is displayed
  - [x] Ensure confirmation page is formatted cleanly
- [ ] Windows phone
  - [ ] Ensure login page is formatted cleanly
  - [ ] Attempt to login with missing fields, ensure error is displayed
  - [ ] Attempt to login as an invalid user, ensure error is displayed
  - [ ] Login successfully, ensure you're routed to the landing page
  - [ ] Ensure landing page is formatted cleanly
  - [ ] Attempt to begin certification, ensure you're routed to the first week of questions
  - [ ] Ensure certification questions are formatted cleanly
  - [ ] Across the various weeks, ensure that the followup questions for 1, 6, and 7 are formatted cleanly
  - [ ] Attempt to continue without filling out every field, ensure error is displayed
  - [ ] Go to previous weeks and ensure your answers are still filled out correctly
  - [ ] On the last week's page, attempt to submit without checking the box and ensure error is displayed
  - [ ] Attempt to submit, ensure confirmation page is displayed
  - [ ] Ensure confirmation page is formatted cleanly

**Comment by KevinJBoyer** [comment]
Notes on testing in on a Samsung Galaxy S7 & Chrome:
- I'm not getting a follow up question for either answer (yes/no) on question 2.
- For the follow up question on #1, if you omit answering, there's no indication of the error on clicking "Next, Certify Week X." The button visibly depresses but there's no indication that something went wrong until you scroll back up and see the red error test.

**Comment by kalvinwang** [comment]
@KevinJBoyer on your first bullet, there's no followup question for #2, the instructions meant to say 6 not 2 (and now they do)

**Comment by KevinJBoyer** [comment]
Thanks! I also went back to check the follow-up error on Q7 that John noticed and confirmed it's happening on Android + Chrome too

**Comment by jdelloso** [comment]
Here is the summary of mobile device testing:


Browser | Device | Test Vehicle | Results
- Safari | iPhone 7 | Actual Device | Failed on PUA Q7 (Ticket #400)
- Safari | iPad Pro 12.9 | Actual Device | Failed on PUA Q7 (Ticket #400)
- Chrome | Samsung Galaxy 7 | Browserstack.com | In Progress
- Internet Explorer | Windows Phone |   | Not Started

There appears to be multiple issues on Galaxy 7 Chrome.
No testing has been done on Windows Phone.  Do we really need to test this?

Please correct any mistakes.

**Comment by KevinJBoyer** [comment]
@jdelloso -- my owh testing on SG7 + Chrome didn't show any issues besides PUA Q7 ticket #400. Is the reference above to your own test?

**Comment by jdelloso** [comment]
I was looking at the checking boxes at the top and two were unchecked.

**Comment by jdelloso** [comment]
Corrected Update:

Here is the summary of mobile device testing:

Browser | Device | Test Vehicle | Results

Safari | iPhone 7 | Actual Device | Failed on PUA Q7 (Ticket #400)
Safari | iPad Pro 12.9 | Actual Device | Failed on PUA Q7 (Ticket #400)
Chrome | Samsung Galaxy 7 | Browserstack.com | Failed on PUA Q7 (Ticket #400)
Internet Explorer | Windows Phone |   | Not Started
