### ISSUE TITLE
UAT content fixes - round 2

### ISSUE THREAD

**Issue by mthong** [cagov/unemployment#399]
Make the below content fixes identified during review by UIB and PAB on Thursday. 

These edits are captured in the active draft document as "suggestions" with additional comments. 

- [ ] Add "* Indicates required text" at the top of the authentication form, similar to the BPO login page (see image below)

- [ ] Add "with or" back in the sentence "Enter your Social Security number with or without dashes." (It currently says "Enter your Social Security number without dashes.") 

- [ ] Change timeout message to: "You were logged out after 30 minutes of inactivity. Provide your information again to certify your weeks.” (Currently says: "We logged you out after 30 minutes of inactivity. Please provide your information again to certify your weeks.")  

<img width="1207" alt="Screen Shot 2020-06-25 at 8 37 39 PM" src="https://user-images.githubusercontent.com/4636824/85819840-c8e1ba00-b729-11ea-8fe3-a1649425ee9b.png">

**Comment by mkhandekar** [comment]
@sharonwarner this is ready to go. The changes only take place on the authentication page and are highlighted in yellow.
[Retroactive Certification – Application Content – ACTIVE DRAFT](https://docs.google.com/document/d/1WdMsc_nId5PH7qFLwCFlTImLU1SiQ0QhtJA3OfYBNbo/edit#)
