### ISSUE TITLE
UAT content fixes - English

### ISSUE THREAD

**Issue by mthong** [cagov/unemployment#422]
- [x] Remove “(optional)” from the “Address Line 2” field for all three versions of the form (UI FT, UI PT, PUA). The field should still be optional (i.e. it can be left blank), just remove the text from the field label. 
- [x] Capitalize ZIP for the field label (currently "Zip") and also capitalize ZIP in the help text for all three versions of the form (UI FT, UI PT, PUA). 
- [x] Add bold to the words “as instructed by EDD” to the help test for Q2 of the UI PT form. Also, delete “the” in front of “the EDD” in the same phrase. 
- [x] Add bold to Q5 “Yes” for the UI PT form

Note: these changes only need to be made in the English version. Spanish content tweaks are listed in a separate Github issue. 

@mkhandekar, @nguyen-tina  - I have updated our Active Draft Questions and Help Text sheet with these changes, with affected cells colored bright blue. 

**Screenshot of Address Line 2 field: remove (optional) **
<img width="654" alt="optional address field 2" src="https://user-images.githubusercontent.com/4636824/85970247-bdd39780-b97e-11ea-9627-926ec9113412.png">

**Screenshot of ZIP code field: capitalize ZIP  
<img width="353" alt="ZIP code" src="https://user-images.githubusercontent.com/4636824/85973328-42c2af00-b987-11ea-9807-4760129e4c57.png">

**Screenshot of Q2 for UI PT form: bold "as instructed by EDD" and remove "the" before EDD**
<img width="629" alt="as instructed by EDD" src="https://user-images.githubusercontent.com/4636824/85970485-7f8aa800-b97f-11ea-80cf-182a79471356.png">

** Screenshot of Q5 of the UI PT form (DE 4581PT): bold "Yes" in the question**
<img width="503" alt="Q5_UIPT_boldyes" src="https://user-images.githubusercontent.com/4636824/85970726-2a9b6180-b980-11ea-8e2e-9a564148cbfb.png">
