### ISSUE TITLE
UAT content fixes - Spanish

### ISSUE THREAD

**Issue by mthong** [cagov/unemployment#425]
All these changes are highlighted in bright blue cells in Nava's Active Draft for Questions and Help Text.

- [ ] All forms Q6 Employer Field (UI FT, UI PT, PUA): Update gross earnings label from "Salarios/Sueldos ganados en bruto antes de deducciones con este empleador (sin importar si le pagaron o no)" to "Ingresos en bruto antes de deducciones con este empleador (sin importar si le pagaron o no)." 

<img width="571" alt="All Forms Help Text Q6 - Spanish" src="https://user-images.githubusercontent.com/4636824/85986171-aad1bf00-b9a0-11ea-9716-22726d9714de.png">

- [ ] PUA Question 2: Remove extra question mark after “tiempo completo?”
<img width="557" alt="PUA Q2 remove extra question mark" src="https://user-images.githubusercontent.com/4636824/85986092-8e358700-b9a0-11ea-967d-8d07203c8c5a.png">

- [ ] PUA Question 4 – Help Text. Bold "Sí" 
Si rechazó un trabajo, se le agendará una una cita para hacer determinación. Los miembros de un sindicato/unión, marquen **Sí** si rechazaron una referencia del sindicato/unión para un trabajo.
<img width="545" alt="Q4 bold" src="https://user-images.githubusercontent.com/4636824/85986109-94c3fe80-b9a0-11ea-8b6e-e45fdc347adc.png">

- [ ] UI FT Question 5 – Help Text
Bold the "Sí" in Marque Sí únicamente si la escuela o el entrenamiento laboral comenzó durante esta semana de trabajo. 
<img width="608" alt="UI FT Q5 Spanish" src="https://user-images.githubusercontent.com/4636824/85986161-a7d6ce80-b9a0-11ea-8963-d14cbb4d83e6.png">
