### ISSUE TITLE
Follow-ups on detailed confirmation page

### ISSUE THREAD

**Issue by kalvinwang** [cagov/unemployment#489]
Some additional tasks that came up while working on #487, which we decided to leave for a subsequent PR in order to get the detailed confirmation page onto staging for UAT testing:

 - ~Print CSS should expand all sections~ (separated into #491)
- [x]  Make entire gray bar clickable not just the title text (done in #501)
- [x] Refactor to reuse common code per TODOs in code (done in #501 and in #503)
- [x] Actually add snapshots (done in #501 and in #503)
- ~Log some of the errors in Azure per TODOs in code~ (separated into #505)

**Comment by kalvinwang** [comment]
@sharonwarner i separated the last item into its own ticket here: https://github.com/cagov/unemployment/issues/505
