### ISSUE TITLE
Recruit and schedule research participants

### ISSUE THREAD

**Issue by mthong** [cagov/unemployment#553]
As a researcher on the claim status sprint, I want to be able to gather and align on the script we'll be using during research sessions. 

- [x] Recruit and schedule research participants (10 max)
  - [x] Identify subset of participants
  - [x] See if we have those kinds of participants in Ethnio
  - [x] If not, open up a new screener
  - [x] If yes, reach out to them and schedule 
  - [x] Schedule them for W2 

- [x] Create calendar (in excel file) with research schedule. 
  - This will also be used for stakeholders to sign up to observe sessions

**Comment by mkhandekar** [comment]
This is done!
