### ISSUE TITLE
Coordinate August round of UIO and SMS claimant notifications

### ISSUE THREAD

**Issue by mthong** [cagov/unemployment#580]
- [x] Prep, conduct and follow-up 8/18 meeting
- [x] Prep, conduct and follow-up 8/20 meeting
- [x] Prep, conduct and follow-up 8/25 meeting
- [x] Prep, conduct and follow-up 8/27 meeting
