### ISSUE TITLE
Align on top findings from research

### ISSUE THREAD

**Issue by mthong** [cagov/unemployment#583]
- [x] Midpoint check-in on Mon 8/24
- [x] Synthesis workshop on Wed 8/26
- [x] Draft recommendations on Thur 8/27 - 8/28 
- [x] Share out at Sprint Demo on Mon 8/31
