### ISSUE TITLE
Organize design and research closeout documentation on all projects

### ISSUE THREAD

**Issue by mthong** [cagov/unemployment#598]
Ensure relevant documentation from design and development of our work is up-to-date and organized for future reference:
- [x] [unemployment guide](https://docs.google.com/document/d/14BfuWRxq-ozpZp7VH0-uLQSLAXw_B7h8rUvY95ftZz4/edit#heading=h.btmq99envykh)
- [x] [retroactive certification app](https://docs.google.com/document/d/17ceZD-Jw_kppTPxO7le-JBreofLQHgrBIqJpc1QCWn0/edit) (claimant and staff)
- [x] [claim status ](https://docs.google.com/document/d/1gm6UfCtpsMAghIfXrlhDvG7Vs4G0ruayAFTgNJjM1MU/edit#heading=h.btmq99envykh)

**Comment by nguyen-tina** [comment]
I've reviewed all three! Next, I'll work on updating the Table of Contents. 

Michelle, please review and fill in any product blanks where you can :)
