### ISSUE TITLE
Develop mid-fidelity mocks and user flow for Claim Tracker MVP

### ISSUE THREAD

**Issue by nguyen-tina** [cagov/unemployment#619]
- [x] Identify use-cases (user stories, narratives) to inform user flows
- [x] Coordinate with PM to ensure requirements are documented @mthong 
- [x] Explore and determine design system to use
- [x] Partner with engineering to sign-off on design system @kalvinwang 
- [x] Create a prototype in Figma to illustrate key flows and interactions
