### ISSUE TITLE
Provide project management for November retro-cert communications 

### ISSUE THREAD

**Issue by mthong** [cagov/unemployment#626]
- [x] Ensure new SMS and UIO messages have been finalized and translated
- [x] Ensure new SMS and UIO messages have been prepared and tested 
- [x] Ensure list of claimants to be contacted has been prepared
- [x] Ensure Week 1 SMS messages have been sent 
- [ ] Ensure Week 2 SMS messages have been sent 
- [x] Ensure UIO messages have been sent
