### ISSUE TITLE
Research | Guide | Synthesize usability research

### ISSUE THREAD

**Issue by mkhandekar** [cagov/unemployment#89]
Now that we're at the end of [usability testing the MVP application](https://github.com/cagov/benefits-screener/issues/22), we need to synthesize what we learned so that we can:
* Make content changes on high priority pain points from research and design team feedback
* Document longer term recommendations 

Sprint 2: 8 pts
Sprint 3: 5 pts

Tina
- [x] Synthesize research
- [x] Gather recommendations from reseaerch

Meghana
- [x] Incorporate content questions
- [x] Incorporate medium/long-term changes
- [x] Incorporate Tamar's content feedback
- [x] Add Meghan's content feedback

**Comment by mthong** [comment]
Here are some high level questions from product perspective. You may already be addressing these in your findings. 

The vision for the guide (formerly screener) was to "_give potential applicants easy-to-follow guidance on how to apply for UI benefits, so they can get through the process easily and quickly._" 

The goal was to "_reduce the uncertainty and frustration experienced by potential applicants who are currently unable to find clear information about whether, when and how to apply for unemployment benefits._"

Questions that follow from this:
* Were we able to distill complex requirements into easy to follow guidance that users correctly understood? 
* Did users come away from the guide with a clear and accurate understanding of what action to take next? 
* What did we learn about how easy or difficult it was for users to "find themselves" or the specific cases that applied to them in the way we organized the content? (Also related to an earlier assumption that targeted guidance would be helpful when we thought we'd develop customized guidance based on short set of screening questions)
* What evidence do we have that the guide would be successful at reducing uncertainty? At reducing frustration? 
* What are the limitations of the guide in reducing uncertainty and frustration?

**Comment by mkhandekar** [comment]
Synthesis is complete; we have a couple new tickets to track how we will share the findings and recommendations.
