### ISSUE TITLE
Content | Iterate on content 

### ISSUE THREAD

**Issue by mkhandekar** [cagov/unemployment#90]
_This is a continuation of https://github.com/cagov/benefits-screener/issues/15 based on user feedback and EDD / UI SME feedback._

### User story
As a designer/researcher, I need to write policy-compliant, plain-language at 6th grade level, trauma-informed content, so that...
1. potential applicants can understand if and when they will be able to apply and receive UI benefits, and 
2. the screener is design and built to match current EDD constraints and needs 

### Acceptance criteria
- [ ] Content must be at or below 6th grade reading level (using [Hemmingway App](http://www.hemingwayapp.com/))
- [ ] Content for each screen is drafted
- [ ] Content for each screen is reviewed by:
  - [ ] stakeholders, including EDD policy SMEs
  - [ ] content strategy SMEs, such as Corey Mahoney (who drove the [Content Style Guide for the CA Covid-19 website](https://docs.google.com/document/d/1txYjL0T2Qmi6Bn7UMtRyECNGbJpOzVQ5ALtqrVTOPOI/edit)) and potentially Nava content strategy teammates
- [ ] Content for each screen is finalized
- [ ] Content for each screen is documented with implementation notes for engineering team

**Comment by mkhandekar** [comment]
I'm going to put this back in the backlog because we made changes to the Guide covered by other tickets. It's also in a stable place right now, with Spanish translation already complete. We can pick it back up when we implement some of our recommendations based on research.

**Comment by mkhandekar** [comment]
Actually, going to just close it, we can open up new tickets when we're ready to iterate specific portions of the Guide.
